[package]
name = "sidereal-sim-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sidereal-core = { path = "../sidereal-core" }
serde = { version = "1.0", features = ["derive"] }
