[package]
name = "sidereal-client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy.workspace = true
bevy_remote.workspace = true
sidereal-core = { path = "../../crates/sidereal-core" }
